Modif metrics
datascience-ufc/asd pull request #9
Opened 2019-03-03 03:24 UTC by matheus-frota

# Pull Request
* Adicionando um modelo baseline em Decision Tree
* Criação de uma função para plotagem de uma matriz de confusão
* Adicionando uma função de cálculos de métricas de uma matriz de confusão

2019-03-03 03:29 UTC, ryukinix requested changes
Alguns conselhos e sugestões nos comentários abaixo. Parabéns pelo modelo! Achei bem legal!

2019-03-03 03:29 UTC, ryukinix commented on asd/metrics.py
> +
Acho que essa função deveria retornar um dicionário com cada uma das métricas invés de apenas imprimir os resultados.

Dessa maneira cada uma das métricas podem ser utilizadas posteriormente para criar gráficos ou reports mais elaborados.

2019-03-03 03:30 UTC, matheus-frota commented on asd/metrics.py
> +
Verdade, não tinha pensado nisso.
Vlw @ryukinix, vou aplicar essas dicas.

2019-03-03 13:08 UTC, ryukinix commented
Os testes não estão passando, verifique os detalhes aqui: https://travis-ci.org/datascience-ufc/asd/builds/500987746?utm_source=github_status&utm_medium=notification

2019-03-03 13:09 UTC, ryukinix commented
Está relacionado ao estilo do código que não está competível com o [PEP-8]. Por favor utilize o flake8 para buscar os erros.

[PEP-8]: https://www.python.org/dev/peps/pep-0008/

2019-03-07 02:35 UTC, ryukinix approved these changes

2019-03-07 02:36 UTC, ryukinix commented
Ótimas modificações. Este PR está bom agora. Irei fazer merge.

2019-03-07 02:36 UTC, merged